version: '3.8'
services:
    redis:
        image: redislabs/redismod
        ports:
          - "16379:6379"
        volumes:
          - $PWD/data:/data
        command: --dir /data --loadmodule /usr/lib/redis/modules/rejson.so
    app:
        restart: always
        build: .
        ports:
            - "8081:80"
        depends_on:
            - redis
    test:
        build: .
        volumes:
            - $PWD:/app
        depends_on:
            - redis
        entrypoint: "pytest -s"